"""changed watering to water

Revision ID: 2225b0c5b79f
Revises: ef150d00ba5b
Create Date: 2023-11-28 12:09:12.349307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2225b0c5b79f'
down_revision = 'ef150d00ba5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('water', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('extra_info', sa.String(), nullable=True))
        batch_op.alter_column('size',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.drop_column('watering')
        batch_op.drop_column('extra_care')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra_care', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('watering', sa.VARCHAR(), nullable=True))
        batch_op.alter_column('size',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('extra_info')
        batch_op.drop_column('water')

    # ### end Alembic commands ###
